project:
  type: website
  title: "Análisis in situ"
  output-dir: docs

website:
  title: "GAB 2023"
  reader-mode: false
  search: false
  navbar:
    background: "#546e7a"
    foreground: "#ffffff"
    right:
      - icon: github
        href: https://ppaccioretti.github.io/PISAA_GAB2023/
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: escala_lote.qmd
        text: "Escala fina"
      - href: escala_regional.qmd
        text: "Escala regional"
    page-footer:
      background: "#546e7a"
      right:
        - text: '&#169; 2023 Pablo Paccioretti, Mariano Córdoba <span xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:18px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:18px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>'

lang: es
citations-hover: true
knitr:
  opts_chunk:
    #collapse: true
    comment: "##"
    # results: "hold"
format:
  html:
    theme: [zephyr]
    #self-contained: true
    toc: true
    toc-location: left
    toc-title: Contenidos
    title-block-categories: false
    # df-print: kable
    #monofont: "Roboto Mono"
    #mainfont: "Roboto"
    code-tools: true
    code-link: false
    highlight-style: arrow
    #title-block-banner: "#546e7a"
    #title-block-banner-color: "white"
    code-block-bg: true
    code-block-background: true
    code-block-border-left: true
    #code-overflow: "wrap"
    fontsize: 12pt
    code-overflow: "scroll"
    #code-line-numbers: true
